// Cross-post AI Glimpse articles to Medium, Dev.to, and Hashnode with
// canonical_url pointing back at aiglimpse.ai. The platforms attribute
// the original to us in search engines while we earn a real backlink
// from each (DA 96, 89, 80).
//
// Quality gating: short news bites are skipped to avoid spammy syndication.
// Each platform has its own threshold and category filter.
//
// Persistence: data/syndicated.json records which slug went to which
// platform with the returned URL, so re-runs don't double-post.

import fs from 'node:fs/promises';
import path from 'node:path';

const STATE_PATH = path.join(process.cwd(), 'data', 'syndicated.json');

async function loadState() {
  try { return JSON.parse(await fs.readFile(STATE_PATH, 'utf8')); }
  catch { return { articles: {} }; }
}

async function saveState(state) {
  await fs.mkdir(path.dirname(STATE_PATH), { recursive: true });
  await fs.writeFile(STATE_PATH, JSON.stringify(state, null, 2));
}

// ---------------------------------------------------------------------------
// HTML to Markdown conversion
// ---------------------------------------------------------------------------
// Our article HTML is generated by us and follows a tight subset
// (h2, h3, p, ul, ol, li, a, strong, em, img, figure, blockquote), so
// a regex-based converter is sufficient and avoids pulling in a 200KB
// dependency for the build runner.

function htmlToMarkdown(html) {
  let md = html;
  md = md.replace(/<figure[^>]*>\s*<img[^>]*src="([^"]+)"[^>]*alt="([^"]*)"[^>]*>\s*(?:<figcaption[^>]*>([\s\S]*?)<\/figcaption>)?\s*<\/figure>/gi,
    (_, src, alt, cap) => `\n\n![${alt}](${src})${cap ? `\n*${cap.replace(/<[^>]+>/g, '').trim()}*` : ''}\n\n`);
  md = md.replace(/<img[^>]*src="([^"]+)"[^>]*alt="([^"]*)"[^>]*>/gi, (_, src, alt) => `\n\n![${alt}](${src})\n\n`);
  md = md.replace(/<h3[^>]*>([\s\S]*?)<\/h3>/gi, (_, c) => `\n\n### ${c.replace(/<[^>]+>/g, '').trim()}\n\n`);
  md = md.replace(/<h2[^>]*>([\s\S]*?)<\/h2>/gi, (_, c) => `\n\n## ${c.replace(/<[^>]+>/g, '').trim()}\n\n`);
  md = md.replace(/<blockquote[^>]*>([\s\S]*?)<\/blockquote>/gi, (_, c) => `\n\n> ${c.replace(/<\/?p[^>]*>/gi, '').replace(/<[^>]+>/g, '').trim()}\n\n`);
  md = md.replace(/<strong[^>]*>([\s\S]*?)<\/strong>/gi, '**$1**');
  md = md.replace(/<b[^>]*>([\s\S]*?)<\/b>/gi, '**$1**');
  md = md.replace(/<em[^>]*>([\s\S]*?)<\/em>/gi, '*$1*');
  md = md.replace(/<i[^>]*>([\s\S]*?)<\/i>/gi, '*$1*');
  md = md.replace(/<a[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi, (_, href, text) => `[${text.replace(/<[^>]+>/g, '').trim()}](${href})`);
  md = md.replace(/<li[^>]*>([\s\S]*?)<\/li>/gi, (_, c) => `- ${c.replace(/<[^>]+>/g, '').trim()}\n`);
  md = md.replace(/<\/?(ul|ol)[^>]*>/gi, '\n');
  md = md.replace(/<p[^>]*>([\s\S]*?)<\/p>/gi, (_, c) => `\n\n${c.trim()}\n\n`);
  md = md.replace(/<br\s*\/?>/gi, '\n');
  md = md.replace(/<[^>]+>/g, '');
  md = md.replace(/\n{3,}/g, '\n\n').trim();
  return md;
}

// Normalize a tag string for platforms that only accept alphanumerics.
function normalizeTag(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]/g, '');
}

// ---------------------------------------------------------------------------
// Medium
// ---------------------------------------------------------------------------
// API: https://github.com/Medium/medium-api-docs
// Accepts contentFormat: 'html' so we POST the article HTML as-is.

async function mediumGetUserId(token) {
  const res = await fetch('https://api.medium.com/v1/me', {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' }
  });
  if (!res.ok) throw new Error(`medium /me ${res.status}: ${await res.text()}`);
  const json = await res.json();
  return json.data.id;
}

async function crosspostMedium(article, token) {
  const userId = await mediumGetUserId(token);
  const body = {
    title: article.title,
    contentFormat: 'html',
    content: `<h1>${article.title}</h1>\n${article.subtitle ? `<p><em>${article.subtitle}</em></p>\n` : ''}${article.html_body}\n<hr><p><em>This article was originally published on <a href="${article.canonical_url}">AI Glimpse</a>.</em></p>`,
    canonicalUrl: article.canonical_url,
    tags: (article.tags || []).slice(0, 5).map(t => String(t).slice(0, 25)),
    publishStatus: 'public'
  };
  const res = await fetch(`https://api.medium.com/v1/users/${userId}/posts`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    body: JSON.stringify(body)
  });
  if (!res.ok) throw new Error(`medium posts ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const json = await res.json();
  return json.data.url;
}

// ---------------------------------------------------------------------------
// Dev.to
// ---------------------------------------------------------------------------
// API: https://developers.forem.com/api/v1
// Requires markdown. Tags must be alphanumeric, lowercase, max 4.

async function crosspostDevto(article, key) {
  const tags = (article.tags || []).map(normalizeTag).filter(t => t.length >= 3).slice(0, 4);
  const body = {
    article: {
      title: article.title,
      body_markdown: `${article.subtitle ? `_${article.subtitle}_\n\n` : ''}${article.markdown_body}\n\n---\n\n_This article was originally published on [AI Glimpse](${article.canonical_url})._`,
      published: true,
      canonical_url: article.canonical_url,
      tags,
      description: article.excerpt || article.subtitle || ''
    }
  };
  const res = await fetch('https://dev.to/api/articles', {
    method: 'POST',
    headers: { 'api-key': key, 'Content-Type': 'application/json', Accept: 'application/vnd.forem.api-v1+json' },
    body: JSON.stringify(body)
  });
  if (!res.ok) throw new Error(`devto ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const json = await res.json();
  return json.url;
}

// ---------------------------------------------------------------------------
// Hashnode
// ---------------------------------------------------------------------------
// API: https://apidocs.hashnode.com/  (GraphQL at https://gql.hashnode.com)
// Requires publicationId, which we cache after first run.

async function hashnodeGetPublicationId(token) {
  const q = `query { me { publications(first: 1) { edges { node { id title } } } } }`;
  const res = await fetch('https://gql.hashnode.com', {
    method: 'POST',
    headers: { Authorization: token, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: q })
  });
  // Hashnode retired free GraphQL API access on 2026-05-13. Unpaid
  // requests now 301 to the announcement page, so we receive HTML instead
  // of JSON. Surface a useful error rather than the JSON parser barf.
  const ctype = res.headers.get('content-type') || '';
  if (!ctype.includes('application/json')) {
    throw new Error('hashnode API is now Pro-plan-only. Upgrade at hashnode.com/billing or unset HASHNODE_TOKEN to skip.');
  }
  if (!res.ok) throw new Error(`hashnode me ${res.status}: ${await res.text()}`);
  const json = await res.json();
  const edge = json?.data?.me?.publications?.edges?.[0];
  if (!edge) throw new Error('hashnode: user has no publication. Create one at hashnode.com/create-blog');
  return edge.node.id;
}

async function crosspostHashnode(article, token, publicationId) {
  const tags = (article.tags || []).map(t => ({
    name: String(t).slice(0, 25),
    slug: normalizeTag(t)
  })).filter(t => t.slug.length >= 2).slice(0, 5);

  const q = `mutation Publish($input: PublishPostInput!) { publishPost(input: $input) { post { id url } } }`;
  const variables = {
    input: {
      title: article.title,
      subtitle: article.subtitle || undefined,
      contentMarkdown: `${article.markdown_body}\n\n---\n\n_Originally published on [AI Glimpse](${article.canonical_url})._`,
      tags,
      publicationId,
      originalArticleURL: article.canonical_url,
      settings: { isNewsletterActivated: false }
    }
  };
  const res = await fetch('https://gql.hashnode.com', {
    method: 'POST',
    headers: { Authorization: token, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: q, variables })
  });
  if (!res.ok) throw new Error(`hashnode publish ${res.status}: ${await res.text()}`);
  const json = await res.json();
  if (json.errors) throw new Error(`hashnode: ${JSON.stringify(json.errors).slice(0, 200)}`);
  return json.data.publishPost.post.url;
}

// ---------------------------------------------------------------------------
// Quality gates
// ---------------------------------------------------------------------------
// Skip short news pieces (< 500 words). Skip ethics/business/robotics on
// Dev.to and Hashnode since those audiences expect technical content.

const TECHNICAL_CATEGORIES = new Set(['llms', 'tools', 'research', 'industry']);

// Dev.to and Hashnode happily accept short technical posts (their own
// community publishes 200-400 word notes all the time). News-length
// articles are valuable backlinks even if brief, as long as they fit the
// technical audience. Medium keeps a higher bar.
function shouldSyndicate(article) {
  return {
    medium: article.word_count >= 600,
    devto: article.word_count >= 300 && TECHNICAL_CATEGORIES.has(article.category),
    hashnode: article.word_count >= 300 && TECHNICAL_CATEGORIES.has(article.category)
  };
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export async function syndicate(article) {
  const mediumToken = process.env.MEDIUM_TOKEN;
  const devtoKey = process.env.DEVTO_API_KEY;
  const hashnodeToken = process.env.HASHNODE_TOKEN;

  if (!mediumToken && !devtoKey && !hashnodeToken) {
    return { skipped: true, reason: 'no platform tokens configured' };
  }

  const state = await loadState();
  if (state.articles[article.slug]) {
    return { skipped: true, reason: 'already syndicated', existing: state.articles[article.slug] };
  }

  // Convert HTML body to markdown once (Dev.to + Hashnode need it).
  if (!article.markdown_body) {
    article.markdown_body = htmlToMarkdown(article.html_body);
  }

  const gates = shouldSyndicate(article);
  const results = { medium: null, devto: null, hashnode: null, errors: {}, gates, word_count: article.word_count, category: article.category };
  const haveTokens = { medium: !!mediumToken, devto: !!devtoKey, hashnode: !!hashnodeToken };
  results.tokens_present = haveTokens;

  if (mediumToken && gates.medium) {
    try { results.medium = await crosspostMedium(article, mediumToken); }
    catch (e) { results.errors.medium = e.message; }
  }
  if (devtoKey && gates.devto) {
    try { results.devto = await crosspostDevto(article, devtoKey); }
    catch (e) { results.errors.devto = e.message; }
  }
  if (hashnodeToken && gates.hashnode) {
    try {
      const pubId = state.hashnode_publication_id || await hashnodeGetPublicationId(hashnodeToken);
      state.hashnode_publication_id = pubId;
      results.hashnode = await crosspostHashnode(article, hashnodeToken, pubId);
    } catch (e) { results.errors.hashnode = e.message; }
  }

  // Persist if at least one platform succeeded.
  if (results.medium || results.devto || results.hashnode) {
    state.articles[article.slug] = {
      syndicated_at: new Date().toISOString(),
      ...results,
      errors: Object.keys(results.errors).length > 0 ? results.errors : undefined
    };
    await saveState(state);
  }

  return results;
}

export function syndicationStats(state) {
  const counts = { medium: 0, devto: 0, hashnode: 0, total: Object.keys(state.articles || {}).length };
  for (const a of Object.values(state.articles || {})) {
    if (a.medium) counts.medium++;
    if (a.devto) counts.devto++;
    if (a.hashnode) counts.hashnode++;
  }
  return counts;
}
